# Generated by Django 5.2 on 2025-05-13 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'Umannotated'), (2, 'Annotated'), (3, 'Finished Annotation')], default=1)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('saved', models.BooleanField(default=False)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('annotated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
